In [15]:
import pandas as pd
import numpy as np

In [16]:
data=pd.read_excel('data2.xlsx')

In [17]:
data.head()

InvoiceNo  Unnamed: 1 StockCode                         Description  \
0     541431         NaN     23166      MEDIUM CERAMIC TOP STORAGE JAR   
1     581180         NaN     23497        CLASSIC CHROME BICYCLE BELL    
2     581180         NaN     23552        BICYCLE PUNCTURE REPAIR KIT    
3     581180         NaN     21064               BOOM BOX SPEAKER BOYS   
4     581180         NaN    84625A  PINK NEW BAROQUECANDLESTICK CANDLE   

   Quantity         InvoiceDate  UnitPrice  CustomerID  
0     74215 2011-01-18 10:01:00       1.04       12346  
1        12 2011-12-07 15:52:00       1.45       12347  
2         6 2011-12-07 15:52:00       2.08       12347  
3        24 2011-12-07 15:52:00       1.25       12347  
4        24 2011-12-07 15:52:00       0.85       12347

In [18]:
data[['InvoiceNo', 'CustomerID']]

InvoiceNo  CustomerID
0          541431       12346
1          581180       12347
2          581180       12347
3          581180       12347
4          581180       12347
...           ...         ...
396332     554065       18287
396333     554065       18287
396334     554065       18287
396335     554065       18287
396336     554065       18287

[396337 rows x 2 columns]

In [19]:
clustdata=pd.read_excel('final-clustered-data-1.xlsx', index_col=0)

In [20]:
clustdata.head()

CustomerID  Frequency      Recency  Monetary  R  F  M  RFM  indgroup3  \
0       12346          1  3635.582639  77183.60  1  1  5    7          2   
1       12347          7  3312.338889   4310.00  5  5  5   15          0   
2       12348          4  3385.449306   1437.24  2  4  4   10          0   
3       12349          1  3328.589583   1457.55  4  2  4   10          1   
4       12350          1  3620.332639    294.40  1  1  2    4          2   

   indgroup5  ...  indgroup10  combgroup3  combgroup5  combgroup8  \
0          4  ...           7           2           4           5   
1          3  ...           3           1           3           0   
2          4  ...           0           2           1           2   
3          0  ...           7           2           1           2   
4          1  ...           1           0           0           3   

   combgroup10  dbscan  agg3  agg5  agg8  agg10  
0            6      -1     2     0     5      5  
1            4       0     1     2     0      4  
2            3      -1     0     3     2      0  
3            3      -1     0     3     7      7  
4            8       1     2     0     3      3  

[5 rows x 21 columns]

In [21]:
cdata=clustdata[['CustomerID', 'combgroup5']]
cdata

CustomerID  combgroup5
0          12346           4
1          12347           3
2          12348           1
3          12349           1
4          12350           0
...          ...         ...
4329       18280           0
4330       18281           0
4331       18282           2
4332       18283           3
4333       18287           1

[4334 rows x 2 columns]

In [22]:
data1=data[['InvoiceNo', 'CustomerID', 'StockCode']]
data1

InvoiceNo  CustomerID StockCode
0          541431       12346     23166
1          581180       12347     23497
2          581180       12347     23552
3          581180       12347     21064
4          581180       12347    84625A
...           ...         ...       ...
396332     554065       18287    85040A
396333     554065       18287    85039B
396334     554065       18287    85039B
396335     554065       18287    85040A
396336     554065       18287    72349B

[396337 rows x 3 columns]

In [23]:
cdata

CustomerID  combgroup5
0          12346           4
1          12347           3
2          12348           1
3          12349           1
4          12350           0
...          ...         ...
4329       18280           0
4330       18281           0
4331       18282           2
4332       18283           3
4333       18287           1

[4334 rows x 2 columns]

In [24]:
out = (data1.merge(cdata, left_on='CustomerID', right_on='CustomerID')
          .reindex(columns=['InvoiceNo', 'CustomerID', 'StockCode', 'combgroup5']))

In [25]:
out

InvoiceNo  CustomerID StockCode  combgroup5
0          541431       12346     23166           4
1          581180       12347     23497           3
2          581180       12347     23552           3
3          581180       12347     21064           3
4          581180       12347    84625A           3
...           ...         ...       ...         ...
396332     554065       18287    85040A           1
396333     554065       18287    85039B           1
396334     554065       18287    85039B           1
396335     554065       18287    85040A           1
396336     554065       18287    72349B           1

[396337 rows x 4 columns]

In [26]:
data2=out[['InvoiceNo', 'StockCode', 'combgroup5']]
data2

InvoiceNo StockCode  combgroup5
0          541431     23166           4
1          581180     23497           3
2          581180     23552           3
3          581180     21064           3
4          581180    84625A           3
...           ...       ...         ...
396332     554065    85040A           1
396333     554065    85039B           1
396334     554065    85039B           1
396335     554065    85040A           1
396336     554065    72349B           1

[396337 rows x 3 columns]

In [27]:
data2.describe

<bound method NDFrame.describe of         InvoiceNo StockCode  combgroup5
0          541431     23166           4
1          581180     23497           3
2          581180     23552           3
3          581180     21064           3
4          581180    84625A           3
...           ...       ...         ...
396332     554065    85040A           1
396333     554065    85039B           1
396334     554065    85039B           1
396335     554065    85040A           1
396336     554065    72349B           1

[396337 rows x 3 columns]>

In [28]:
data2.dtypes

InvoiceNo      int64
StockCode     object
combgroup5     int64
dtype: object

In [29]:
type('ABS')

str

In [30]:
data2 = data2.astype({'StockCode': 'str'})

In [31]:
data2[['StockCode']].dtypes

StockCode    object
dtype: object

In [32]:
data2=data2.sort_values(by=['StockCode', 'combgroup5'], ascending=True)


In [33]:
data2.head(20)

InvoiceNo StockCode  combgroup5
296913     538069     10002           0
379608     536863     10002           0
21667      541277     10002           1
254484     536382     10002           1
270942     541615     10002           1
315702     548702     10002           1
315716     543806     10002           1
329017     548714     10002           1
384081     541262     10002           1
384780     550272     10002           1
11722      541491     10002           2
32980      543179     10002           2
255898     540732     10002           2
380779     544634     10002           2
7370       541518     10002           3
16472      536370     10002           3
20117      541631     10002           3
22462      542735     10002           3
23097      540239     10002           3
23152      538093     10002           3

In [34]:
n=5
for i in range(0, n):
    print(i)
    print(clustdata.loc[clustdata['combgroup'+str(n)] == i]['RFM'].unique())

0
[4 3 5]
1
[10 12 11]
2
[8 9]
3
[15 13 14]
4
[7 6]


In [35]:
# vip-group 3 will come first
# # non-vip order-[1, 2, 4, 0]

In [36]:
data2['combgroup5']=pd.Categorical(data2['combgroup5'], [3, 1, 2, 4, 0])
data2

InvoiceNo StockCode combgroup5
296913     538069     10002          0
379608     536863     10002          0
21667      541277     10002          1
254484     536382     10002          1
270942     541615     10002          1
...           ...       ...        ...
91037      580691    90214W          2
91038      580691    90214Y          2
148570     580996    90214Y          2
151695     553503    90214Y          3
91039      580691    90214Z          2

[396337 rows x 3 columns]

In [42]:
findata1=data2.sort_values(by=['StockCode', 'combgroup5'])


In [46]:
findata1[findata1['StockCode']=='10002']

InvoiceNo StockCode combgroup5
7370       541518     10002          3
16472      536370     10002          3
20117      541631     10002          3
22462      542735     10002          3
23097      540239     10002          3
23152      538093     10002          3
27168      548606     10002          3
27248      542629     10002          3
27255      538196     10002          3
31777      541248     10002          3
38034      547223     10002          3
38184      538890     10002          3
47974      537047     10002          3
56157      542610     10002          3
60706      541849     10002          3
61406      541094     10002          3
94532      544935     10002          3
124436     540277     10002          3
142947     550452     10002          3
162805     546790     10002          3
162858     541698     10002          3
162879     539322     10002          3
162906     538167     10002          3
167015     547063     10002          3
180012     538255     10002          3
210386     544278     10002          3
218042     545637     10002          3
219508     547729     10002          3
219689     537770     10002          3
287197     538593     10002          3
323783     542096     10002          3
332842     540798     10002          3
353786     537227     10002          3
21667      541277     10002          1
254484     536382     10002          1
270942     541615     10002          1
315702     548702     10002          1
315716     543806     10002          1
329017     548714     10002          1
384081     541262     10002          1
384780     550272     10002          1
11722      541491     10002          2
32980      543179     10002          2
255898     540732     10002          2
380779     544634     10002          2
38391      538086     10002          4
297389     538853     10002          4
296913     538069     10002          0
379608     536863     10002          0

In [49]:
findata1['InvoiceNo'].split(findata['combgroup5'])

AttributeError: 'Series' object has no attribute 'split'